<?php
include "connessione.php";
session_start();
if (!isset($_SESSION['id'])) {
    header("Location: login.php?err=Accesso negato");
        exit;
        }

        $id_utente = $_SESSION['id'];

        // Query commesse dell’utente loggato
        $query_commesse = "
            SELECT * FROM COMMESSA 
                WHERE REFERENTE_ID = $id_utente 
                    ORDER BY ID DESC
                    ";
                    $result_commesse = $connessione->query($query_commesse);
                    ?>

                    <!DOCTYPE html>
                    <html lang="it">
                    <head>
                      <meta charset="UTF-8">
                        <title>Le Tue Commesse</title>
                          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
                          </head>
                          <body class="bg-light">
                          <div class="container py-5">

                            <div class="d-flex justify-content-between align-items-center mb-4">
                              <h1>📂 Le Tue Commesse</h1>
                                <div>
                                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modalNuovaCommessa">+ Nuova Commessa</button>
                                        <a href="logout.php" class="btn btn-danger ms-2">🚪 Logout</a>
                                          </div>
                                          </div>

                                            <!-- MODAL NUOVA COMMESSA -->
                                              <div class="modal fade" id="modalNuovaCommessa" tabindex="-1" aria-labelledby="modalNuovaCommessaLabel" aria-hidden="true">
                                                  <div class="modal-dialog modal-lg modal-dialog-scrollable">
                                                        <div class="modal-content">
                                                                <div class="modal-header bg-success text-white">
                                                                          <h5 class="modal-title" id="modalNuovaCommessaLabel">➕ Nuova Commessa</h5>
                                                                                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                                                                                            </div>
                                                                                                    <div class="modal-body">
                                                                                                              <form action="inserisci_commessa.php" method="POST" class="row g-3">
                                                                                                                          <div class="col-12">
                                                                                                                                        <label for="nome" class="form-label">Codice Commessa</label>
                                                                                                                                                      <input type="text" name="nome" id="nome" class="form-control" required>
                                                                                                                                                                  </div>
                                                                                                                                                                              <div class="col-12">
                                                                                                                                                                                            <label for="intestatario" class="form-label">Intestatario</label>
                                                                                                                                                                                                          <input type="text" name="intestatario" id="intestatario" class="form-control" required>
                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                  <div class="col-12">
                                                                                                                                                                                                                                                <label for="descrizione" class="form-label">Descrizione</label>
                                                                                                                                                                                                                                                              <textarea name="descrizione" id="descrizione" class="form-control" rows="3"></textarea>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                      <input type="hidden" name="referente_id" value="<?= $id_utente ?>">
                                                                                                                                                                                                                                                                                                  <div class="col-12 d-grid">
                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-success">Salva Commessa</button>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                            <!-- TABELLA COMMESSE -->
                                                                                                                                                                                                                                                                                                                                                              <div class="table-responsive mt-4">
                                                                                                                                                                                                                                                                                                                                                                  <table class="table table-bordered table-striped align-middle">
                                                                                                                                                                                                                                                                                                                                                                        <thead class="table-dark">
                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                          <th>ID</th>
                                                                                                                                                                                                                                                                                                                                                                                                    <th>Intestatario</th>
                                                                                                                                                                                                                                                                                                                                                                                                              <th>Descrizione</th>
                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Azioni</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php while ($commessa = $result_commesse->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td><?= htmlspecialchars($commessa['nome']) ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><?= htmlspecialchars($commessa['INTESTATARIO']) ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td><?= htmlspecialchars($commessa['DESCRIZIONE']) ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td class="d-flex gap-2 flex-wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="home.php?id_commessa=<?= urlencode($commessa['ID']) ?>" class="btn btn-primary btn-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            📌 Vedi Attività
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="modificacommessa.php?id=<?= urlencode($commessa['ID']) ?>" class="btn btn-warning btn-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ✏️ Modifica
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="elimina_commessa.php?id=<?= urlencode($commessa['ID']) ?>" class="btn btn-danger btn-sm" onclick="return confirm('Sei sicuro di voler eliminare questa commessa?');">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    🗑️ Elimina
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
</div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>